[build]
builder = "nixpacks"
buildCommand = "npm ci --omit=dev"

[deploy]
startCommand = "node ./bin/www"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
PORT = "4000"
NODE_ENV = "production"