[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node ./bin/www"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[environment]
PORT = "4000"
NODE_ENV = "production"